# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookSouls' do

  	pod 'JSONModel'
	pod 'IQKeyboardManager'
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~>4.0’
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'Google/SignIn'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'JSONModel'
	pod 'Fabric'
	pod 'Crashlytics'
end
