# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookSouls' do

  	pod 'JSONModel'
	pod 'IQKeyboardManager'
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~>4.0’
	pod 'MBProgressHUD', '~> 1.0.0'

end
